# Generated by Django 5.2.1 on 2025-05-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_country', models.CharField(max_length=100)),
                ('target_city', models.CharField(max_length=100)),
                ('target_name', models.CharField(max_length=200)),
                ('target_sin', models.CharField(max_length=500)),
            ],
        ),
    ]
